name: pytest

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: goanpeca/setup-miniconda@v1.0.2
        with:
          auto-update-conda: true
          activate-environment: topy
          environment-file: conda.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Install ToPy
        shell: bash -l {0}
        run: |
          pip install .

      - name: Run pytest with benchmark
        shell: bash -l {0}
        run: |
          pytest --benchmark-json benchmark.json

      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Python Benchmark with pytest-benchmark
          tool: "pytest"
          output-file-path: benchmark.json
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: true
          alert-threshold: "200%"
